### ISSUE TITLE
stl2pov: error constructing declaration variable?

### ISSUE THREAD

**Issue by kjcole** [rsmith-nl/stltools#7]
Dashes where there should be underscores perhaps? At least that's my guess. POV-Ray wasn't happy with "-" in the declaration variable name, and complained with:

`File 'assembly_v4_rev3.inc' line 3: Parse Error: Expected '=', - found instead`

The first three lines of the file generated by stl2pov:

```
// on Mon Aug 21 17:55:36 2017.
// Source file name: 'assembly_v4_rev3.stl'
# declare m_MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH-MESH = mesh {
```

(It's a Monty Python variable name. I just want to sing "mesh, mesh, mesh, mesh".)

**Comment by rsmith-nl** [comment]
Look at the pov-ray manual. According to the [identifiers](http://www.povray.org/documentation/3.7.0/r3_3.html#r3_3_1_3) section, only letters, digits and underscore are allowed in identifiers. And they can only be 40 characters long. Right off the bat, I see a couple of options (there can be many more).

The easiest option would be to for `stl2pov` to do nothing except document the name requirements, leaving it up to the user to supply a suitable name. Let's call that option 1.

Another option would be to cut the name from the STL file to 38 characters, preprend the `m_`, analyse the remaining name  and bomb when it contains illegal characters. That is option 2.

Option 3 could be to e.g. take the SHA1 hash of the input filename and encode that with base64. That would yield a pretty unique but certainly valid name.

Option 4 could be to supply an option for an object name base, e.g. `foo`.
The generated meshes would then be `m_foo_1`, `m_foo_2` et cetera.
Of course the given string (`foo`) would be checked for validity before using it.

Option 2 and 3 are not backwards compatible. So at the moment I'm most inclined to stick with option 1. :-)

But option 4 might be worthwhile, since the name of an STL object depends on the software that makes it, which isn't always under the user's control.

**Comment by kjcole** [comment]
I discovered your software because I have an STL that I didn't create (from Thingiverse) and I've been exploring ways to change it back to something programmatic / parameterized. 

I've documented a set of steps to "sort of" turn it into a true OpenSCAD source file by grabbing SVG projections and then converting the SVG path in each to a series of polygons. (http://wiki.hacdc.org/index.php/STL_to_SCAD).

It's been a while since I used POV-Ray (https://opensource.com/life/16/2/povray) but the first thing I did was rename that variable from your conversion program. (I have no idea where it came up with MESH-MESH-...-MESH.)

Hence, option 4 would be the direction I might go.

**Comment by rsmith-nl** [comment]
The name for the mesh is based on the object name from the STL file.

After having given the problem some thought, I decided to up the version number and go with option 3. This will generate a predictable but short and valid name.

Since it is rather trivial for the user to change the name of the mesh afterwards if they so desire, I think this should be good enough.

I might have inadvertantly dropped some functionality in `stl2pdf` w.r.t. colours from the old master branch when I merged the develop branch. I'll fix that before uploading and tagging the new 5.0.
