### ISSUE TITLE
Problem decoding certain stl files

### ISSUE THREAD

**Issue by pp-kaitlyn** [rsmith-nl/stltools#8]
I have a few stl files (that I cannot share, unfortunately) that are causing an error when using stl2pov.py. it throws this error: 'utf8' codec can't decode byte 0x9e in position 6: invalid start byte. 
Interestingly, it it gives the same byte and position for each file. After some reading on stack overflow, it seems there is a character at that location that is not ascii. Any theories as to how to fix this? Any thoughts are appreciated.

**Comment by rsmith-nl** [comment]
When reading an STL file, this library *assumes* UTF-8 input.

As a short-term solution, you can try opening the STL file in an editor and remove non-UTF-8 characters from (presumably) the object name.

As a long-term solution I see two possibilities:

- Return the name as a `bytes` string.
- Specify the encoding to try when opening the file.

Personally, I'm leaning toward the first solution, because it sidesteps encoding issues altogether. The objects name is generally not hugely important.

**Comment by rsmith-nl** [comment]
Having looked into the issue, the object name is actually used in quite a lot of places in the code. :-( So using the name as `bytes` is not an option.

Initially, I modified the code to handle encodings explicitly. But that only shifts the problem to the user since it requires the user to *know* the encoding of the object name, which is not really practical.

As a simpler solution I've modified the `decode` commands to replace errors with �, since this does not require user intervention. See example below.

    In [1]: test = b'this \x9e is a test'

    In [2]: test.decode('utf-8')
    ---------------------------------------------------------------------------
    UnicodeDecodeError                        Traceback (most recent call last)
    <ipython-input-2-89793aa4a5e1> in <module>()
    ----> 1 test.decode('utf-8')
    
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 5: invalid start byte

    In [3]: test.decode('utf-8', errors='replace')
    Out[3]: 'this � is a test'

This change is commit `7480539`. It should solve your problem.

**Comment by pp-kaitlyn** [comment]
Thanks for the quick response! Just to make sure I understand: this means binary stls must be converted to be put through stl2pov?

**Comment by pp-kaitlyn** [comment]
It does not work with my specific files. Still getting:
> 'utf8' codec can't decode byte 0x9e in position 6: invalid start byte
The first 84 characters of these stls look something like this: COLOR=<some bytes indicating color> MATERIAL=<some bytes indicating material> SOLID
I fixed this by detecting if the header contains b'COLOR and replacing the header with something generic that stl2pov can handle in _parsebinary. This allows the name to be decoded properly when name.decode(encoding) is called.

**Comment by pp-kaitlyn** [comment]
I can write a pull request soon. Will comment when complete
